### ISSUE TITLE
Intimidating Shout has an incorrect level requirement

### ISSUE THREAD

**Issue by alecjpav** [fusionpit/WhatsTraining#12]
Hello,

As you can see here, Intimidating Shout says it's ready to be trained now and I am level 20, but the trainer window says it requires level 22.

![WoWScrnShot_083119_190005](https://user-images.githubusercontent.com/28431403/64070894-e3d6c100-cc21-11e9-8b73-b9b37705d484.jpg)

![WoWScrnShot_083119_190016](https://user-images.githubusercontent.com/28431403/64070895-e5a08480-cc21-11e9-887a-c57b4692285c.jpg)

Not sure if this is a one off thing or if there are other abilities/spells for all classes that are incorrect, but this is the first one I've come across. I'll report them if I see any more. Thanks for the addon!

**Comment by fusionpit** [comment]
Thank you!  The shaman spell "Cure Disease" is also part of the incorrect level.  Guess the repack I originally got the data from isn't totally accurate.

**Comment by fusionpit** [comment]
This has been fixed in version 1.6.1.
