### ISSUE TITLE
zhTW Localization

### ISSUE THREAD

**Issue by class2u** [fusionpit/WhatsTraining#16]
Thank you for making this great addon. Here are the Traditional Chinese (zhTW) translations. :)

AVAILABLE_HEADER = "現在可以訓練",
MISSINGREQS_HEADER = "可以訓練但是缺少需求條件",
NEXTLEVEL_HEADER = "即將可以訓練",
NOTLEVEL_HEADER = "還不可以訓練",
MISSINGTALENT_HEADER = "缺少需要的天賦",
IGNORED_HEADER = "已忽略",
KNOWN_HEADER = "已學會",
PET_HEADER = "寵物技能",
COST_FORMAT = "花費: %s",
TOTALCOST_FORMAT = "總需花費: %s",
TOTALSAVINGS_FORMAT = "總共省下: %s",
LEVEL_FORMAT = "等級 %s",
TAB_TEXT = "我可以接受什麼訓練?"

**Comment by fusionpit** [comment]
Thanks you so much!  This will be put into the next release.

**Comment by fusionpit** [comment]
Released as part of 1.8.1
