### ISSUE TITLE
WOTLK

### ISSUE THREAD

**Issue by Jorvanus** [fusionpit/WhatsTraining#24]
I love this when levelling, any plans for updating to WOTLK?

Take this as a highlight of interest, rather than a nag.

**Comment by Sakatard** [comment]
I've updated it for wrath classic using old data from 3.3.5, everything should work but it has not been fully tested on every class
https://github.com/Sakatard/WhatsTraining

**Comment by Sakatard** [comment]
updated it and used data from a 3.3.5 fork, added a pull request
https://github.com/fusionpit/WhatsTraining/pull/25

**Comment by KoolKeith** [comment]
I can't live without it, Mr. Pit :)

**Comment by Sakatard** [comment]
> I can't live without it, Mr. Pit :)

you can just pull my fork for now
