### ISSUE TITLE
update needed for WoW - CATA Classic, bug-report/error-message

### ISSUE THREAD

**Issue by MelchiorGaspar** [fusionpit/WhatsTraining#28]
WhatsTraining, addon (v5.0.3) wrath

1x WhatsTraining/Cache.lua:16: Usage: NonEmptySpell:ContinueOnLoad(callbackFunction)
[string "=[C]"]: in function `error'
[string "@Blizzard_ObjectAPI/Classic/Spell.lua"]:53: in function `ContinueOnSpellLoad'
[string "@WhatsTraining/Cache.lua"]:16: in function `CacheSpell'
[string "@WhatsTraining/WhatsTraining.lua"]:279: in main chunk

Locals:
(*temporary) = "Usage: NonEmptySpell:ContinueOnLoad(callbackFunction)"

**Comment by fusionpit** [comment]
Hi there,
Cata classic will not be supported.

**Comment by MelchiorGaspar** [comment]
hi @fusionpit 
not supported, ooh?!
why not?
too much work or maybe not needed anymore...
ooh right no more ranks to spells...
ok nvm thx for your reply.

I will uninstall it for CATA-classic then.

**Comment by fusionpit** [comment]
@MelchiorGaspar Thanks to the work of [Venomisto](https://legacy.curseforge.com/members/venomisto/projects), this addon has been updated for Cataclysm classic!

**Comment by MelchiorGaspar** [comment]
ooh! ty for the heads up and Venomisto too.
