### ISSUE TITLE
toc bump to (v1.15.3) from v1.15.2.  classic-Era.

### ISSUE THREAD

**Issue by MelchiorGaspar** [fusionpit/WhatsTraining#30]
hi Devs thx so much for a useful addon..
I just wanted to bring to your attention that this addons needs a toc bump..
v1.15.2 --> v1.15.3
please and thx.

**Comment by fusionpit** [comment]
Thanks for letting me know! This has been done.

**Comment by MelchiorGaspar** [comment]
ok ty. yeah its a great addon for classic as it helps me know whats up next to train and its cost... way kool.
