### ISSUE TITLE
bump toc for WoW-classic-Era (v1.15.5)

### ISSUE THREAD

**Issue by MelchiorGaspar** [fusionpit/WhatsTraining#32]
WoW-Classic-Era just got an update today to (v1.15.5) 
WOW!
and could at the very least use a toc bump..
once the game is active around 6pm EST USA..

I will report back any LUA errors I way find,
unless some one else does it first.

**Comment by fusionpit** [comment]
done!

**Comment by MelchiorGaspar** [comment]
Hey Fusionpit, TY so much for an update.
and thx for a handy WoW addon.

no errors to report, as I mentioned above I didn't find any issues yet.
