### ISSUE TITLE
[SUGGESTION] Separate Warlock Grimoires by Minion

### ISSUE THREAD

**Issue by GsynthChris** [fusionpit/WhatsTraining#33]
Hello,

I was wondering if it would be possible to reorder the Warlock Pet Abilities list so its separated by pet type, then by level.

**Comment by fusionpit** [comment]
This is a good idea, and it aligns perfectly with some recent work with Warlocks I have been doing. I will need to level a warlock up a bit, because Succubus and Incubus minions are trained separately and that throws a wrench into things.

**Comment by fusionpit** [comment]
Implemented this in 8.0.0
