### ISSUE TITLE
Sayaad Icons appearing in all vendor panes

### ISSUE THREAD

**Issue by tykelley** [fusionpit/WhatsTraining#36]
After the most recent update, I am seeing the Sayaad icons near each item in the vendor pane -- this is true even with WhatsTraining as the only active addon. Disabling the WhatsTraining addon fixes the issue. I have attached an image of a random vendor pane and a /fstack .

![image](https://github.com/user-attachments/assets/44cb8a92-23c2-431c-8e46-e0b10975104b)
![image](https://github.com/user-attachments/assets/86408579-ee03-462f-983d-c67a9260a2f7)

**Comment by fusionpit** [comment]
Thank you for the report. This should be fixed in 8.0.1.
